services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mudar123"
      MYSQL_DATABASE: "unicesumar"
    ports:
      - "3306:3306"
  
  adminer: 
    image: adminer
    ports:
      - 8080:8080
#docker compose up -d
# -> essario criar as seguintes tabelas 
#----------- Tabela categories ------------#
  # CREATE TABLE categories (
  #id INT AUTO_INCREMENT PRIMARY KEY,
  #name VARCHAR(255) NOT NULL,
  #created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  #updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
#----------- Tabela users ------------#
  #CREATE TABLE users (
  #id INT AUTO_INCREMENT PRIMARY KEY,
  #usuario VARCHAR(255) NOT NULL,
  #Email VARCHAR(14) NOT NULL UNIQUE,
  #nome VARCHAR(255) NOT NULL,
  #senha VARCHAR(255) NOT NULL),
  #papel ENUM('Usuário', 'Administrador') DEFAULT 'Usuário');

